// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for StatusFunction
 */
export interface StatusFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/app/status/status.
 */
export class StatusFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: StatusFunctionProps) {
    super(scope, id, {
      description: 'src/app/status/status.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/app/status/status.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}